spring:
  application:
    name: reportes
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto : none

  datasource:
    driver : org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:compose-postgres}
    password: ${DB_PASSWORD:compose-postgres}
jwt:
  cookieExpiry: 36000