DO $$
BEGIN
    CREATE TABLE IF NOT EXISTS public.users (
    	id int8 NOT NULL,
    	password varchar(255) NULL,
    	username varchar(255) NULL,
    	CONSTRAINT users_pkey PRIMARY KEY (id)
    );

    IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'users' AND schemaname = 'public') THEN
        INSERT INTO public.users
        (  id,password, username)
        VALUES(1,'$2a$10$JzSnRX2J2SDgRTYQFDutkeV4hvBPnmF2eLpBK7p2fXiEASxYfFrGq', 'rector');


    CREATE TABLE IF NOT EXISTS public.roles (
        	id int8 NOT NULL,
            name varchar(255) NULL,
            CONSTRAINT roles_pkey PRIMARY KEY (id)
        );

    IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'roles' AND schemaname = 'public') THEN
            INSERT INTO public.roles
            (id,name)
            VALUES(1,'RECTOR');
            INSERT INTO public.roles
            (name)
            VALUES('STUDENT');

    CREATE TABLE IF NOT EXISTS public.users_roles (
            	CREATE TABLE public.users_roles (
                	roles_id int8 NOT NULL,
                	user_entity_id int8 NOT NULL,
                	CONSTRAINT users_roles_pkey PRIMARY KEY (roles_id, user_entity_id)
                );


                ALTER TABLE public.users_roles ADD CONSTRAINT FK_rolid FOREIGN KEY (roles_id) REFERENCES public.roles(id);
                ALTER TABLE public.users_roles ADD CONSTRAINT FK_user_id FOREIGN KEY (user_id) REFERENCES public.users(id);
            );

        IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'users_roles' AND schemaname = 'public') THEN
                INSERT INTO public.users_roles
                (roles_id, user_id)
                VALUES(1, 1);

        CREATE TABLE IF NOT EXISTS public.course (
            CREATE TABLE public.course (
            	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
            	course varchar(255) NULL,
            	course_translation varchar(255) NULL,
            	CONSTRAINT course_entity_course_key UNIQUE (course),
            	CONSTRAINT course_entity_pkey PRIMARY KEY (id)
            );

        IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'course' AND schemaname = 'public') THEN
            INSERT INTO public.course_entity
            (course, course_translation)
            VALUES( 'Matemeticas', 'Matematicas');
            INSERT INTO public.course_entity
            (course, course_translation)
            VALUES( 'Fisicas', 'Fisica');
            INSERT INTO public.course_entity
            (course, course_translation)
            VALUES( 'Ciencias', 'Ciencias');

CREATE TABLE IF NOT EXISTS public.course (
            -- public.grades_entity definition

            -- Drop table

            -- DROP TABLE public.grades_entity;

            CREATE TABLE public.grades (
            	grade float8 NULL,
            	course_id int8 NULL,
            	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
            	user_id int8 NULL,
            	CONSTRAINT course_user_entity_pkey PRIMARY KEY (id)
            );

            ALTER TABLE public.grades_entity ADD CONSTRAINT fk9sp2tthbyyia94dfgwpsibe8f FOREIGN KEY (user_id) REFERENCES public.users(id);
            ALTER TABLE public.grades_entity ADD CONSTRAINT fkldqw7w06j2nsmfcgmvjdd09n3 FOREIGN KEY (course_id) REFERENCES public.course_entity(id);
    END IF;
END $$;