CREATE TABLE public.users (
	id int8 NOT NULL,
	"password" varchar(255) NULL,
	username varchar(255) NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);

INSERT INTO public.users
        (  id,password, username)
        VALUES(0,'$2a$10$JzSnRX2J2SDgRTYQFDutkeV4hvBPnmF2eLpBK7p2fXiEASxYfFrGq', 'rector');

CREATE TABLE public.roles (
	id int8 NOT NULL,
	"name" varchar(255) NULL,
	CONSTRAINT roles_pkey PRIMARY KEY (id)
);

         INSERT INTO public.roles
            (id,name)
            VALUES(1,'RECTOR');
            INSERT INTO public.roles
            (id,name)
            VALUES(2,'STUDENT');


CREATE TABLE public.users_roles (
	roles_id int8 NOT NULL,
	user_entity_id int8 NOT NULL,
	CONSTRAINT users_roles_pkey PRIMARY KEY (roles_id,user_entity_id)
);


ALTER TABLE public.users_roles ADD CONSTRAINT fk7v417qhe0i2m9h8njggvciv00 FOREIGN KEY (user_entity_id) REFERENCES public.users(id);
ALTER TABLE public.users_roles ADD CONSTRAINT fka62j07k5mhgifpp955h37ponj FOREIGN KEY (roles_id) REFERENCES public.roles(id);

                    INSERT INTO public.users_roles
                (roles_id, user_entity_id)
                VALUES(1, 0);

CREATE TABLE public.course (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	course varchar(255) NULL,
	course_translation varchar(255) NULL,
	CONSTRAINT course_course_key UNIQUE (course),
	CONSTRAINT course_pkey PRIMARY KEY (id)
);

                           INSERT INTO public.course
            (course, course_translation)
            VALUES( 'Matemeticas', 'Matematicas');
            INSERT INTO public.course
            (course, course_translation)
            VALUES( 'Fisicas', 'Fisica');
            INSERT INTO public.course
            (course, course_translation)
            VALUES( 'Ciencias', 'Ciencias');

CREATE TABLE public.grade (
	grade float8 NULL,
	course_id int8 NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NULL,
	CONSTRAINT grade_pkey PRIMARY KEY (id)
);


ALTER TABLE public.grade ADD CONSTRAINT fk7e8ca7hfmrpruicqhocskjlf2 FOREIGN KEY (course_id) REFERENCES public.course(id);
ALTER TABLE public.grade ADD CONSTRAINT fkobx49ylgv13u0bfh9lau61xvu FOREIGN KEY (user_id) REFERENCES public.users(id);
